name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  get-version:
    runs-on:  ubuntu-latest
    outputs:
      release_version: ${{ steps.get_release_version.outputs.release_version }}
    steps:
    - name: Get release version
      id: get_release_version
      run: echo ::set-output name=release_version::${GITHUB_REF#refs/*/}
    - name: Check output
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.release_version }}
      run: |
        echo $RELEASE_VERSION
        echo ${{ steps.vars.outputs.release_version }}

  publish-helm-charts:
    runs-on:  ubuntu-latest
    needs: get-version
    env:
      HELM_VERSION: v2.16.9
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          export_default_credentials: true
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: gcloud auth configure-docker --quiet
      - name: Validate chart versions
        run: make lint-versions
      - name: Remove previous Helm
        run: sudo rm -rf $(which helm)
      - name: Install Helm
        run: ./infra/scripts/install-helm.sh
      - name: Publish Helm charts
        run: ./infra/scripts/sync-helm-charts.sh